UserManagement/Models/ErrorViewModel.cs
namespace UserManagement.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UserManagement/Models/RegisterModel.cs
namespace UserManagement.Models
{
    public class RegisterModel
    {
        public string? Name { get; set; }
        public string? Email { get; set; }
        public string? MobileNumber { get; set; }
        public string? Address { get; set; }
        public string? Password { get; set; }
    }
}

UserManagement/Models/ResponseModel.cs
namespace UserManagement.Models
{
    public class ResponseModel
    {
        public int UserID {  get; set; }
        public string? Email { get; set; }
        public string? mobile { get; set; }
        public string? Name { get; set; }
        public string? Address { get; set; }
        public string? message { get; set; }
        public Boolean status { get; set; }
    }
}

UserManagement/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace UserManagement.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear(); 
            return RedirectToAction("Index", "Login"); 
        }
    }
}

UserManagement/Controllers/DashbordController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Reflection;
using System.Xml.Linq;
using UserManagement.Interface;
using UserManagement.Models;

namespace UserManagement.Controllers
{
    public class DashbordController : Controller
    {
        private readonly IDALDashbordcs _reg;


        public DashbordController(IDALDashbordcs reg)
        {
            _reg = reg;
        }
        public IActionResult Index(int id)
        {
            if (HttpContext.Session.GetInt32("UserID") == null)
            {
                
                return RedirectToAction("Index", "Login");
            }
            else
            {
                var userId = HttpContext.Session.GetInt32("UserID");
                var name = HttpContext.Session.GetString("Name");
                var email = HttpContext.Session.GetString("Email");
                var mobile = HttpContext.Session.GetString("MobileNumber");
                var address = HttpContext.Session.GetString("Address");
                
                ViewBag.UserID = userId;
                ViewBag.Name = name;
                ViewBag.Email = email;
                ViewBag.MobileNumber = mobile;
                ViewBag.Address = address;
                var data = _reg.GetUserDetails(userId.Value);
                return View(data);
            }
           
        }


         public IActionResult Update()
        {
            var userId = HttpContext.Session.GetInt32("UserID");
            

           
            var data = _reg.GetUserDetails(userId.Value);
            return View(data);
        }

        public JsonResult UpdateUser(RegisterModel obj)
        {
            ResponseModel result = new ResponseModel();
            result = _reg.UpdateUser(obj);
            return Json(result);
        }
    }
}

UserManagement/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UserManagement.Models;

namespace UserManagement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UserManagement/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using UserManagement.Interface;
using UserManagement.Models;

namespace UserManagement.Controllers
{
    public class LoginController : Controller
    {
        private readonly IDALLogin _reg;

       
        public LoginController(IDALLogin reg)
        {
            _reg = reg;
        }
        public IActionResult Index()
        {
            return View();
        }
        public JsonResult LoginUser(RegisterModel log)
        {
            ResponseModel result = new ResponseModel();
            result = _reg.loginUser(log);
            if (result.status && result.UserID != 0)
            {
                
                HttpContext.Session.SetInt32("UserID", result.UserID);
                HttpContext.Session.SetString("Name", result.Name);
                HttpContext.Session.SetString("Email", result.Email);
                HttpContext.Session.SetString("MobileNumber", result.mobile);
                HttpContext.Session.SetString("Address", result.Address);

                result.message = "Login successful.";
            }
            else
            {
                result.message = "Invalid email or password.";
            }

            return Json(result);
        }

    }
}

UserManagement/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using UserManagement.DAL;
using UserManagement.Interface;
using UserManagement.Models;

namespace UserManagement.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IDALRgister _reg;

        // Use constructor injection to get the instance of IDALRgister
        public RegisterController(IDALRgister reg)
        {
            _reg = reg;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult RegisterUser(RegisterModel reg)
        {
            ResponseModel result = new ResponseModel();
            result = _reg.Register(reg);
            return Json(result);
        }
    }
}

UserManagement/Views/Dashbord/Index.cshtml
@* l
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model UserManagement.Models.RegisterModel
<h2>Dashboard</h2>



<div class="border border-info  w-50 m-auto p-5">

    <p>Name: @Model.Name </p>
    <p>Email: @Model.Email </p>
    <p>Mobile Number: @Model.MobileNumber </p>
    <p>Address: @Model.Address </p>

    <br />
    <button class="btn btn-primary" onclick="updateDetails()">Update Details</button>
</div>

<script>
    function updateDetails() {
        window.location.href = "/Dashbord/Update";
    }
</script>

UserManagement/Views/Dashbord/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model UserManagement.Models.RegisterModel

<div class="container">
    <div class="row justify-content-center">
        <div class="col-5 mt-5 shadow-lg">
            <h1 class="d-flex mb-5 justify-content-center">UPdate User Info</h1>

            <form id="registrationForm">
                <div class="form-group">
                    <label for="name">Name <small class="text-danger">*</small></label>
                    <input type="text" class="form-control" value="@Model.Name" id="name" placeholder="Full Name" required>
                </div>
                <div class="form-group">
                    <label for="email">Email address <small class="text-danger">*</small></label>
                    <input type="email" class="form-control" value="@Model.Email" id="email" placeholder="Email" required readonly>
                   
                </div>
                <div class="form-group">
                    <label for="mobile">Mobile Number <small class="text-danger">*</small></label>
                    <input type="text" class="form-control" value="@Model.MobileNumber" id="mobile" placeholder="Phone Number" required>
                    <span id="phoneValidationStatus" style="color: red;"></span>
                </div>
                <div class="form-group">
                    <label for="address">Address <small class="text-danger">*</small></label>
                    <input type="text" class="form-control" value="@Model.Address" id="address" placeholder="Address" required>
                </div>
               
               
                <button type="button" class="btn btn-primary" onclick="update()">Update Details </button>
            </form>
            <br />

            <br />
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
 <script>
    $(document).ready(function () {

       

        $("#mobile").on('input', function () {  
            checkPhoneValidation();
        });


    });

   

    function checkPhoneValidation() {
        var phone = $("#mobile").val();
        var phoneValidationStatusElement = $("#phoneValidationStatus");


        var phoneRegex = /^\d{10}$/;


        if (phoneRegex.test(phone)) {
            phoneValidationStatusElement.text("Phone number is valid.");
            phoneValidationStatusElement.css("color", "green");
        } else {
            phoneValidationStatusElement.text("Invalid phone number format (10 digits required).");
            phoneValidationStatusElement.css("color", "red");
        }
    }
    function update() {
        var name = $("#name").val();
        var email = $("#email").val();
        var mobile = $("#mobile").val();
        var address = $("#address").val();


        var obj = {
            Name: name,
            Email: email,
            MobileNumber: mobile,
            Address: address
           
        };


        $.ajax({
            type: "POST",
            url: "/Dashbord/UpdateUser",
            data: obj,
            success: function (result) {
                if (result.status) {
                    alert(result.message);
                    window.location.href = '@Url.Action("Index", "Dashbord")'

                } else {
                    alert(result.message);
                    window.location.href = '@Url.Action("Index", "Login")'
                }
            },
            error: function (error) {
                alert("An error occurred during the request.");
                console.error(error);
            }
        });
    }
 </script>

UserManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UserManagement/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>User - Login</title>
    <meta content="" name="description" />
    <meta content="" name="keywords" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UserManagement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>

<body>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-5 mt-5 shadow-lg">
                <h1 class="d-flex mb-5 justify-content-center">User Login</h1>

                <form id="registrationForm">
                   
                    <div class="form-group">
                        <label for="email">Email address <small class="text-danger">*</small></label>
                        <input type="email" class="form-control" id="email" placeholder="Email" required>
                       
                    </div>
                   
                    <div class="form-group">
                        <label for="password">Password <small class="text-danger">*</small></label>
                        <input type="password" class="form-control" id="password" placeholder="Password" required>
                    </div>

                    <button type="button" class="btn btn-primary" onclick="Loginfn()">Login</button>
                </form>
                <br />
               
                <br />
            </div>
        </div>
    </div>

</body>

</html>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
   function Loginfn() {
    var email = $("#email").val();  
    var password = $("#password").val();

    
    if (!email || !password) {  
        alert("Please fill in all fields.");
        return;
    }

    var obj = {
        Email: email,
        Password: password
    };

    $.ajax({
        type: "POST",
        url: "/Login/LoginUser",
        data: obj,  
        success: function (result) {
            if (result.status) {
                alert(result.message);
                    window.location.href = '@Url.Action("Index", "Dashbord")'
               
            } else {
                alert(result.message);
             window.location.href = '@Url.Action("Index", "Login")'
            }
        },
        error: function (error) {
            alert("An error occurred during the request.");
            console.error(error);
        }
    });
}

</script>

UserManagement/Views/Register/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>User - Register</title>
    <meta content="" name="description" />
    <meta content="" name="keywords" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UserManagement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Register" asp-action="Index">UserManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                   
                    <ul class="navbar-nav">
                        @if (Context.Session.GetInt32("UserID") != null)
                        {
                            <li class="nav-item">
                                <span class="nav-link">Hello,@Context.Session.GetString("Name")!</span>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post" class="form-inline">
                                    <button type="submit" class="btn btn-link nav-link">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-5 mt-5 shadow-lg">
                <h1 class="d-flex mb-5 justify-content-center">User Register</h1>

                <form id="registrationForm">
                    <div class="form-group">
                        <label for="name">Name <small class="text-danger">*</small></label>
                        <input type="text" class="form-control" id="name" placeholder="Full Name" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email address <small class="text-danger">*</small></label>
                        <input type="email" class="form-control" id="email" placeholder="Email" required>
                        <span id="emailValidationStatus" style="color: red;"></span>
                    </div>
                    <div class="form-group">
                        <label for="mobile">Mobile Number <small class="text-danger">*</small></label>
                        <input type="text" class="form-control" id="mobile" placeholder="Phone Number" required>
                        <span id="phoneValidationStatus" style="color: red;"></span>
                    </div>
                    <div class="form-group">
                        <label for="address">Address <small class="text-danger">*</small></label>
                        <input type="text" class="form-control" id="address" placeholder="Address" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password <small class="text-danger">*</small></label>
                        <input type="password" class="form-control" id="password" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                        <label for="confirmPassword">Confirm Password <small class="text-danger">*</small></label>
                        <input type="password" class="form-control" id="confirmPassword" placeholder="Confirm Password" required>
                        <span id="passwordMatchStatus" style="color: red;"></span>
                    </div>
                    <button type="button" class="btn btn-primary" onclick="register()">Register</button>
                </form>
                <br />
               
                <br />
            </div>
        </div>
    </div>

</body>

</html>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    $(document).ready(function () {
     
        $("#email").on('input', function () {
            checkEmailValidation();
        });

       
        $("#mobile").on('input', function () {
            checkPhoneValidation();
        });

        
        $("#confirmPassword").on('input', function () {
            checkPasswordMatch();
        });
    });

    function checkEmailValidation() {
        var email = $("#email").val();
        var emailValidationStatusElement = $("#emailValidationStatus");

     
        
        var emailRegex = new RegExp('^[a-zA-Z0-9+_.-]+@@[a-zA-Z0-9.-]+\\.[a-zA-z]{2,3}$');
       
        if (emailRegex.test(email)) {
            emailValidationStatusElement.text("Email is valid.");
            emailValidationStatusElement.css("color", "green");
        } else {
            emailValidationStatusElement.text("Invalid email format.");
            emailValidationStatusElement.css("color", "red");
        }
    }

    function checkPhoneValidation() {
        var phone = $("#mobile").val();
        var phoneValidationStatusElement = $("#phoneValidationStatus");

      
        var phoneRegex = /^\d{10}$/;

      
        if (phoneRegex.test(phone)) {
            phoneValidationStatusElement.text("Phone number is valid.");
            phoneValidationStatusElement.css("color", "green");
        } else {
            phoneValidationStatusElement.text("Invalid phone number format (10 digits required).");
            phoneValidationStatusElement.css("color", "red");
        }
    }

    function checkPasswordMatch() {
        var password = $("#password").val();
        var confirmPassword = $("#confirmPassword").val();
        var matchStatusElement = $("#passwordMatchStatus");

       
        if (password === confirmPassword) {
            matchStatusElement.text("Passwords match.");
            matchStatusElement.css("color", "green");
        } else {
            matchStatusElement.text("Passwords do not match.");
            matchStatusElement.css("color", "red");
        }
    }

    function register() {
        var name = $("#name").val();
        var email = $("#email").val();
        var mobile = $("#mobile").val();
        var address = $("#address").val();
        var password = $("#password").val();
        var confirmPassword = $("#confirmPassword").val();

        // Perform a final validation before submitting the form
        if (!name || !email || !mobile || !address || !password || !confirmPassword) {
            alert("Please fill in all fields.");
            return;
        }

        if (password.length < 6) {
            alert("Password must be at least 6 characters long.");
            return;
        }

        if (password !== confirmPassword) {
            alert("Passwords do not match.");
            return;
        }

        var obj = {
            Name: name,
            Email: email,
            MobileNumber: mobile,
            Address: address,
            Password: password
        };

        $.ajax({
            type: "POST",
            url: "/Register/RegisterUser",
            data: obj,
            success: function (result) {
                if (result.status) {
                    alert(result.message);
                    window.location.href = '@Url.Action("Index", "Login")'
                } else {
                    alert(result.message);
                    window.location.href = '@Url.Action("Register", "Index")'
                }
            },
            error: function (error) {
                alert("An error occurred during the request.");
                console.error(error);
            }
        });
    }
</script>

UserManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UserManagement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UserManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (Context.Session.GetInt32("UserID") != null)
                        {
                            <li class="nav-item">
                                <span class="nav-link">Hello,@Context.Session.GetString("Name")!</span>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post" class="form-inline">
                                    <button type="submit" class="btn btn-link nav-link">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - UserManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>